// Ícones do painel em pixel art 16×16, no traço dos do site ('.' transparente, 'x' = currentColor). Os que o site
// já tem (casa, lupa, mais, check, whatsapp…) vêm de lá; aqui só os que faltavam.
import type { Grade } from '../arte/pixel/grades'
import { icones } from '../arte/pixel/grades'
import { iconesExtras } from '../arte/pixel/extras'
import { iconesAbas } from '../arte/pixel/abas'

function g(linhas: string[]): Grade {
  return { w: linhas[0]?.length ?? 0, h: linhas.length, linhas }
}

const proprios: Record<string, Grade> = {
  // Caixa de importação do rateio (a mesma do site): a fita em cima e o corte tracejado descendo pela frente.
  caixa: g([
    '................',
    '....xxxxxxxx....',
    '...x...xx...x...',
    '..x....xx....x..',
    '.xxxxxxxxxxxxxx.',
    '.x.....xx.....x.',
    '.x.....xx.....x.',
    '.x............x.',
    '.x.....xx.....x.',
    '.x............x.',
    '.x.....xx.....x.',
    '.x............x.',
    '.x.....xx.....x.',
    '.x............x.',
    '.xxxxxxxxxxxxxx.',
    '................',
  ]),
  'caixa-cheia': g([
    '................',
    '....xxxxxxxx....',
    '...xxxx..xxxx...',
    '..xxxxx..xxxxx..',
    '.x............x.',
    '.xxxxxx..xxxxxx.',
    '.xxxxxx..xxxxxx.',
    '.xxxxxxxxxxxxxx.',
    '.xxxxxx..xxxxxx.',
    '.xxxxxxxxxxxxxx.',
    '.xxxxxx..xxxxxx.',
    '.xxxxxxxxxxxxxx.',
    '.xxxxxx..xxxxxx.',
    '.xxxxxxxxxxxxxx.',
    '.xxxxxxxxxxxxxx.',
    '................',
  ]),
  // Criar (o "+" no quadrado do Instagram), com os cantos em degrau.
  criar: g([
    '................',
    '..xxxxxxxxxxxx..',
    '.x............x.',
    '.x............x.',
    '.x.....xx.....x.',
    '.x.....xx.....x.',
    '.x.....xx.....x.',
    '.x..xxxxxxxx..x.',
    '.x..xxxxxxxx..x.',
    '.x.....xx.....x.',
    '.x.....xx.....x.',
    '.x.....xx.....x.',
    '.x............x.',
    '.x............x.',
    '..xxxxxxxxxxxx..',
    '................',
  ]),
  'criar-cheio': g([
    '................',
    '..xxxxxxxxxxxx..',
    '.xxxxxxxxxxxxxx.',
    '.xxxxxxxxxxxxxx.',
    '.xxxxxx..xxxxxx.',
    '.xxxxxx..xxxxxx.',
    '.xxxxxx..xxxxxx.',
    '.xxx........xxx.',
    '.xxx........xxx.',
    '.xxxxxx..xxxxxx.',
    '.xxxxxx..xxxxxx.',
    '.xxxxxx..xxxxxx.',
    '.xxxxxxxxxxxxxx.',
    '.xxxxxxxxxxxxxx.',
    '..xxxxxxxxxxxx..',
    '................',
  ]),
  // Coração cheio: a Atividade aberta (como no Instagram).
  'coracao-cheio': g([
    '................',
    '................',
    '...xxx....xxx...',
    '..xxxxx..xxxxx..',
    '.xxxxxxxxxxxxxx.',
    '.xxxxxxxxxxxxxx.',
    '.xxxxxxxxxxxxxx.',
    '..xxxxxxxxxxxx..',
    '...xxxxxxxxxx...',
    '....xxxxxxxx....',
    '.....xxxxxx.....',
    '......xxxx......',
    '.......xx.......',
    '................',
    '................',
    '................',
  ]),
  // Servidor: duas gavetas de rack com a luz acesa.
  servidor: g([
    '................',
    '.xxxxxxxxxxxxxx.',
    '.x............x.',
    '.x.xx.....xxx.x.',
    '.x............x.',
    '.xxxxxxxxxxxxxx.',
    '................',
    '.xxxxxxxxxxxxxx.',
    '.x............x.',
    '.x.xx.....xxx.x.',
    '.x............x.',
    '.xxxxxxxxxxxxxx.',
    '.......xx.......',
    '.......xx.......',
    '..xxxxxxxxxxxx..',
    '................',
  ]),
  'servidor-cheio': g([
    '................',
    '.xxxxxxxxxxxxxx.',
    '.xxxxxxxxxxxxxx.',
    '.xx..xxxxx...xx.',
    '.xxxxxxxxxxxxxx.',
    '.xxxxxxxxxxxxxx.',
    '................',
    '.xxxxxxxxxxxxxx.',
    '.xxxxxxxxxxxxxx.',
    '.xx..xxxxx...xx.',
    '.xxxxxxxxxxxxxx.',
    '.xxxxxxxxxxxxxx.',
    '.......xx.......',
    '.......xx.......',
    '..xxxxxxxxxxxx..',
    '................',
  ]),
  // Lápis (editar), deitado na diagonal.
  editar: g([
    '................',
    '...........xx...',
    '..........x..x..',
    '.........x....x.',
    '........x....x..',
    '.......x....x...',
    '......x....x....',
    '.....x....x.....',
    '....x....x......',
    '...x....x.......',
    '..x....x........',
    '..xx..x.........',
    '..x.xx..........',
    '..xxx...........',
    '................',
    '................',
  ]),
  // Lixeira.
  lixo: g([
    '................',
    '......xxxx......',
    '.....x....x.....',
    '..xxxxxxxxxxxx..',
    '................',
    '...x........x...',
    '...x..x..x..x...',
    '...x..x..x..x...',
    '...x..x..x..x...',
    '...x..x..x..x...',
    '...x..x..x..x...',
    '...x..x..x..x...',
    '....x......x....',
    '....xxxxxxxx....',
    '................',
    '................',
  ]),
  // Baixar: seta pra baixo caindo na bandeja.
  baixar: g([
    '................',
    '.......xx.......',
    '.......xx.......',
    '.......xx.......',
    '.......xx.......',
    '.......xx.......',
    '....x..xx..x....',
    '.....x.xx.x.....',
    '......xxxx......',
    '.......xx.......',
    '................',
    '.x............x.',
    '.x............x.',
    '.xxxxxxxxxxxxxx.',
    '................',
    '................',
  ]),
  // Câmera (foto do celular).
  camera: g([
    '................',
    '................',
    '.....xxxxxx.....',
    '..xxxx....xxxx..',
    '.x............x.',
    '.x....xxxx....x.',
    '.x...x....x...x.',
    '.x..x......x..x.',
    '.x..x......x..x.',
    '.x...x....x...x.',
    '.x....xxxx....x.',
    '.x............x.',
    '..xxxxxxxxxxxx..',
    '................',
    '................',
    '................',
  ]),
  // Olho (ver no site / prévia).
  olho: g([
    '................',
    '................',
    '................',
    '.....xxxxxx.....',
    '...xx......xx...',
    '..x....xx....x..',
    '.x....xxxx....x.',
    'x....xxxxxx....x',
    '.x....xxxx....x.',
    '..x....xx....x..',
    '...xx......xx...',
    '.....xxxxxx.....',
    '................',
    '................',
    '................',
    '................',
  ]),
  // Sair: porta com a seta saindo.
  sair: g([
    '................',
    '.xxxxxxx........',
    '.x.....x........',
    '.x.....x........',
    '.x.....x...x....',
    '.x.....x....x...',
    '.x...xxxxxxxxx..',
    '.x...xxxxxxxxxx.',
    '.x...xxxxxxxxx..',
    '.x.....x....x...',
    '.x.....x...x....',
    '.x.....x........',
    '.x.....x........',
    '.xxxxxxx........',
    '................',
    '................',
  ]),
  // Pessoa com "+": incluir participante.
  'incluir-pessoa': g([
    '................',
    '.....xxxx.......',
    '....x....x......',
    '...x......x.....',
    '...x......x.....',
    '...x......x.....',
    '....x....x......',
    '.....xxxx...xx..',
    '............xx..',
    '...xxxxxx.xxxxxx',
    '.xx......xxxxxxx',
    'x...........xx..',
    'x...........xx..',
    'x...............',
    'xxxxxxxxxxxxx...',
    '................',
  ]),
  // Atenção: o triângulo com a exclamação.
  atencao: g([
    '................',
    '.......xx.......',
    '......x..x......',
    '......x..x......',
    '.....x....x.....',
    '.....x.xx.x.....',
    '....x..xx..x....',
    '....x..xx..x....',
    '...x...xx...x...',
    '...x...xx...x...',
    '..x..........x..',
    '..x....xx....x..',
    '.x.....xx.....x.',
    '.x............x.',
    'xxxxxxxxxxxxxxxx',
    '................',
  ]),
}

const todos: Record<string, Grade | undefined> = { ...icones, ...iconesExtras, ...(iconesAbas as Record<string, Grade>), ...proprios }

export function grade(nome: string): Grade | undefined {
  return todos[nome]
}
