// Os emblemas dos estados (24×24): o desenho do destaque de cada estado no story de atendimento (InfoStory). Num
// arquivo à parte dos ícones: só o story do estado usa, então eles baixam com ele e não pesam na primeira tela.
import type { Emblema } from '../../dados/canais'
import { tons, validarGrade, type Grade } from './grades'

const e24 = (linhas: string[]): Grade => ({ w: 24, h: 24, linhas, paleta: tons })

/* ───────────────────────── emblemas 24×24 ───────────────────────── */

// Regras do conjunto: madrugada com 4–5 estrelas; chão ou linha d'água sempre na linha 20 e reflexo
// quebrado em 'd' nas linhas 21–23; tudo dentro das colunas 1–22 (1 px de margem, nada sangra);
// luz acesa só na linha d'água ou em 'c'; branco só em pontos (lua, cruz, ponta de cristal, 3 janelas).
export const emblemas: Record<Emblema, Grade> = {
  // RJ: Pão de Açúcar em sino assimétrico com estrias de granito no lado da lua, Morro da Urca baixo,
  // o cabo do bondinho com a cabine, lua crescente e as luzes da orla na água.
  'pao-de-acucar': e24([
    '....................e...',
    '....b...................',
    '..bb.....c......cde.....',
    '.bb............ceede....',
    '.bb............ceced.e..',
    '..bb..........cecede....',
    '....b......e..cceeed....',
    '..............cecede....',
    '.............ececeede...',
    '.......e....e.ceceeed...',
    '..........ee.cccecede...',
    '.....ccceecc.cececeed...',
    '...ccceded...ceeecede...',
    '..ceeeeeded..cececeede..',
    '..eeeeedede.ccceeeeeed..',
    '.eeeeeeededececeeeeede..',
    '.eeeeeeeededceceeeeeede.',
    '.eeeeeeededcececeeeeeed.',
    '.dededededcceeceeeeeede.',
    '.ededededcececeeeeeeeed.',
    '.eeceeeceeeeceeeeceeece.',
    '.dee.dee.d.eed.dee.dee..',
    '..d.d.d.d.d..dd...d...d.',
    '..d.....d.....d.....d...',
  ]),
  // MG / Teófilo Otoni, "capital das pedras preciosas": cacho de cristais prismáticos brutos
  // (turmalina, água-marinha) saindo de uma pedra, com brilho na ponta do maior.
  'pedra-preciosa': e24([
    '........................',
    '........c...............',
    '................e.......',
    '...e...............b....',
    '...........ce.....bbb...',
    '..........ccee.....b....',
    '.........cceedd.........',
    '.........cceedd.........',
    '....ce...cceedd...c.....',
    '....ced..cceedd.cce..e..',
    '....cddd.cceedd.cde.....',
    '..e.cedd.cceeddccedd....',
    '....cceddcceeddcedd.....',
    '.....cdedcceeddcddd.....',
    '.....ccddcceeddced..cc..',
    '..edd.cedcceeddcdeccde..',
    '..cdecededceedeeeeedde..',
    '...cccccdedededededed...',
    '...dedededededededede...',
    '...ededededededededed...',
    '.eeeeeeeeeeeeeeeeeeeeee.',
    '...d.d.d.d.d.d.d.d.d....',
    '......d...d...d...d.....',
    '........d.....d.....d...',
  ]),
  // SP: o Copan com os brises em onda (uma linha sim, uma não) e o Banespa com a antena acesa.
  'predio-sp': e24([
    '.................b......',
    '.........c.......e......',
    '..e..............e......',
    '..............e..e......',
    '.................cd.....',
    '.........cccc....cd...e.',
    '.cc....ccddddc..cded....',
    '.ddccccddccccd..ceed....',
    '.ccddddccddddc.cededd...',
    '.ddccccddccccd.ceeeed...',
    '.ccddddcbddddc.cededd...',
    '.ddccccddccccd.ceeeed...',
    '.ccddddccddddc.cededd...',
    '.ddcbccddccccd.ceeeeded.',
    '.ccddddccddddc.cededdee.',
    '.ddccccddccbcd.ceeeeded.',
    '.ccddddccddddc.cededdee.',
    '.ddccccddccccd.ceeeeded.',
    '.ccddddccddddc.cededdee.',
    '.ddddddddddddd.ceeeeded.',
    '.ceeeeeeeeeeeeceeeeeece.',
    'ee.d.d.d.d.d.eed.d.dee..',
    '..d...d...d....d..d...d.',
    '..d.....d...........d...',
  ]),
  // ES: Convento da Penha no alto do morro, com a torre e a cruz.
  'convento-es': e24([
    '..........b.............',
    '.........bbb....e.......',
    '..........c.........e...',
    '...e.....cce............',
    '.........cde.eeeee......',
    '.........ccecccccce.....',
    '.........ccccccccce.....',
    '......c..ccdcdcdcde.....',
    '.........ccccccccce...e.',
    '........cccceeeeded.....',
    '.......cceeeeeeeeded....',
    '.......ceceeeeeeeede....',
    '......ceceeeeeeeeeede...',
    '.....ceceeeeeeeeeeded...',
    '.....cceeeeeeeeeeeede...',
    '....cceeeeeeeeeeeeeede..',
    '...cceeeeeeeeeeeeeeded..',
    '..cceeeeeeeeeeeeeeeeded.',
    '..ceceeeeeeeeeeeeeeeede.',
    '.ceceeeeeeeeeeeeeeeeded.',
    '.eeceeeeeceeeeeeceeeece.',
    '.dee.d.dee.d.d.eed.dee..',
    '..d.d.d...d...d..dd...d.',
    '..d.....d.....d.....d...',
  ]),
  // SC: ponte Hercílio Luz, com a corrente descendo até encostar no tabuleiro no meio do vão.
  'ponte-sc': e24([
    '........................',
    '...........c.........e..',
    '..e.b..............b....',
    '....ce............ce....',
    '....ce.........e..ce....',
    '...ecec.e........ccee...',
    '....cedc........c.ce....',
    '..e.ce..c......c..ce.e..',
    '..e.ced.c......cd.ce.e..',
    '....ce...c....c...ce....',
    '.e..ced.d.c..cd.d.ce..e.',
    '.e..ce....c..c....ce..e.',
    '....ced.d.dcc.d.d.ce....',
    '.cccccccbccccccbccccccc.',
    '.ededededededededededed.',
    '....ce............ce....',
    '....ce............ce....',
    '....ce............ce....',
    '....ce............ce....',
    '....ce............ce....',
    '.eceeeeeeeeceeeeeeeeece.',
    '.ee..d....ee.......dee..',
    '...d........d.....d...d.',
    '........................',
  ]),
  // Estado ativado no painel, sem desenho próprio: o pino do adesivo de localização fincado na linha do chão, com
  // duas casas ao longe de janela acesa (as mesmas regras: estrelas, chão na 20, reflexo quebrado).
  generico: e24([
    '...................e....',
    '...b....................',
    '.........ccccde.........',
    '.......cccceeeeed.......',
    '......cceeeeeeeeed...e..',
    '......cceeecceeede......',
    '......cceec..deeed......',
    '......ccec....dede......',
    '......ccec....deed......',
    '......cceee..deede......',
    '..e...cceeeeeeeeed......',
    '.......cceeeeeeed.......',
    '.......cceeeeeede...c...',
    '........ceeeeede........',
    '........ceeeeeed........',
    '.........ceeeed......d..',
    '...d.....ceeede....dddd.',
    '.dddd.....cede.....ddcd.',
    '.dcdd.....ceed.....dddd.',
    '.dddd......cd......dddd.',
    '.eeeceeeeeecceeeeeceeee.',
    '..d.d.d.d..dd..d.d.d.d..',
    '....d...d...d.....d.....',
    '..d.....d....d......d...',
  ]),
}

// Em dev, confere tudo já no carregamento (não espera a arte aparecer na tela).
if (import.meta.env?.DEV) {
  for (const [nome, gr] of Object.entries(emblemas)) validarGrade(gr, nome)
}
