// Pixel art de interface, toda em texto. Cada caractere é um pixel:
// '.' transparente, 'x' = currentColor (ícone segue a cor do texto), outras letras vêm da paleta.

import type { Emblema } from '../../dados/canais'

export interface Grade {
  w: number
  h: number
  linhas: string[]
  paleta?: Record<string, string>
}

export const TRANSPARENTE = '.'
export const COR_TEXTO = 'x'

function nova(w: number, h: number, linhas: string[], paleta?: Record<string, string>): Grade {
  return { w, h, linhas, paleta }
}
const i16 = (linhas: string[]) => nova(16, 16, linhas)
const e24 = (linhas: string[], paleta: Record<string, string>) => nova(24, 24, linhas, paleta)

// Confere o desenho em dev: altura, largura de cada linha e letras sem cor. Cada grade é conferida uma vez só.
const conferidas = new WeakSet<Grade>()
export function validarGrade(grade: Grade, nome = 'grade'): boolean {
  if (conferidas.has(grade)) return true
  conferidas.add(grade)
  const erros: string[] = []
  if (grade.linhas.length !== grade.h) erros.push(`${grade.linhas.length} linhas, esperado h=${grade.h}`)
  grade.linhas.forEach((linha, y) => {
    if (linha.length !== grade.w) erros.push(`linha ${y} com ${linha.length} pixels, esperado w=${grade.w}`)
    for (const c of linha) {
      if (c !== TRANSPARENTE && c !== COR_TEXTO && !grade.paleta?.[c]) erros.push(`linha ${y}: "${c}" sem cor na paleta`)
    }
  })
  if (erros.length) console.warn(`[pixel] ${nome}: ${erros.join('; ')}`)
  return erros.length === 0
}

/* ───────────────────────── ícones 16×16 (monocromáticos) ───────────────────────── */

const iconesBase = {
  // Entregador de moto com o baú atrás: o ícone dos destaques "DELIVERY RJ".
  moto: i16([
    '.........xxx....',
    '........xxxxx...',
    '........xxx.x...',
    '.........xxx..x.',
    '.xxxxx..xxxxxxx.',
    '.x...x.xxxx...x.',
    '.x...x.xxxx...x.',
    '.xxxxx.xxxxx..x.',
    '.x...x.xxxx.x.x.',
    '.xxxxx.xxx..x.x.',
    '..x..xxxxxxxxxx.',
    '.xxx......xxx...',
    'x...x....x...x..',
    'x.x.x....x.x.x..',
    'x...x....x...x..',
    '.xxx......xxx...',
  ]),
  // Tigelinha (a cuia do logo), vista de cima em perspectiva.
  cuia: i16([
    '................',
    '................',
    '................',
    '....xxxxxxxx....',
    '..xx........xx..',
    '.x............x.',
    '.xxx........xxx.',
    '.x..xxxxxxxx..x.',
    '.x............x.',
    '..x..........x..',
    '..x..........x..',
    '...x........x...',
    '....xx....xx....',
    '......xxxx......',
    '................',
    '................',
  ]),
  tesoura: i16([
    '................',
    '..x..........x..',
    '..xx........xx..',
    '...xx......xx...',
    '....xx....xx....',
    '.....xx..xx.....',
    '......xxxx......',
    '.......xx.......',
    '......xxxx......',
    '.....xx..xx.....',
    '..xxxx....xxxx..',
    '.x...x....x...x.',
    '.x...x....x...x.',
    '.x...x....x...x.',
    '..xxx......xxx..',
    '................',
  ]),
  sacola: i16([
    '................',
    '......xxxx......',
    '.....x....x.....',
    '....x......x....',
    '....x......x....',
    '.xxxxxxxxxxxxxx.',
    '.x..x......x..x.',
    '.x............x.',
    '.x............x.',
    '.x............x.',
    '.x............x.',
    '.x............x.',
    '.x............x.',
    '.x............x.',
    '.xxxxxxxxxxxxxx.',
    '................',
  ]),
  // Pin do adesivo de localização do Instagram (cheio, com o furo).
  pin: i16([
    '................',
    '.....xxxxxx.....',
    '....xxxxxxxx....',
    '...xxxxxxxxxx...',
    '...xxxx..xxxx...',
    '...xxx....xxx...',
    '...xxx....xxx...',
    '...xxxx..xxxx...',
    '...xxxxxxxxxx...',
    '....xxxxxxxx....',
    '....xxxxxxxx....',
    '.....xxxxxx.....',
    '......xxxx......',
    '.......xx.......',
    '................',
    '................',
  ]),
  lupa: i16([
    '................',
    '....xxxx........',
    '..xx....xx......',
    '..x......x......',
    '.x..xx....x.....',
    '.x.x......x.....',
    '.x........x.....',
    '.x........x.....',
    '..x......x......',
    '..xx....xxx.....',
    '....xxxxxxxx....',
    '..........xxx...',
    '...........xxx..',
    '............xxx.',
    '.............xx.',
    '................',
  ]),
  // Balão de DM com "digitando…".
  balao: i16([
    '................',
    '................',
    '..xxxxxxxxxxxx..',
    '.x............x.',
    '.x............x.',
    '.x............x.',
    '.x..xx.xx.xx..x.',
    '.x..xx.xx.xx..x.',
    '.x............x.',
    '.x............x.',
    '..xx..xxxxxxxx..',
    '...x.x..........',
    '...xx...........',
    '...x............',
    '................',
    '................',
  ]),
  // Aviãozinho de papel do Direct.
  enviar: i16([
    '................',
    '................',
    '.............xx.',
    '...........xxxx.',
    '.........xx.xx..',
    '.......xx..x.x..',
    '.....xx...x.x...',
    '...xx....x..x...',
    '.xx.....x..x....',
    '..xx...x...x....',
    '....xxx...x.....',
    '......x...x.....',
    '.......x.x......',
    '.......x.x......',
    '........x.......',
    '................',
  ]),
  instagram: i16([
    '................',
    '...xxxxxxxxxx...',
    '..x..........x..',
    '.x............x.',
    '.x.........x..x.',
    '.x....xxxx....x.',
    '.x...x....x...x.',
    '.x...x....x...x.',
    '.x...x....x...x.',
    '.x...x....x...x.',
    '.x....xxxx....x.',
    '.x............x.',
    '.x............x.',
    '..x..........x..',
    '...xxxxxxxxxx...',
    '................',
  ]),
  // Balão redondo com telefone (genérico, não é o logo).
  whatsapp: i16([
    '................',
    '......xxxx......',
    '....xx....xx....',
    '...x........x...',
    '..x..xx......x..',
    '..x.xxx......x..',
    '.x..xx........x.',
    '.x..xx........x.',
    '.x...xx..xx...x.',
    '.x....xxxxx...x.',
    '..x....xxx...x..',
    '..x..........x..',
    '..x.......xxx...',
    '.x...xxxxx......',
    '.xxxx...........',
    '................',
  ]),
  relogio: i16([
    '................',
    '......xxxx......',
    '....xx....xx....',
    '...x........x...',
    '..x....x.....x..',
    '..x....x.....x..',
    '.x.....x......x.',
    '.x.....x......x.',
    '.x.....xxxx...x.',
    '.x............x.',
    '..x..........x..',
    '..x..........x..',
    '...x........x...',
    '....xx....xx....',
    '......xxxx......',
    '................',
  ]),
  coracao: i16([
    '................',
    '................',
    '...xxx....xxx...',
    '..x...x..x...x..',
    '.x.....xx.....x.',
    '.x.xx.........x.',
    '.x.x..........x.',
    '..x..........x..',
    '...x........x...',
    '....x......x....',
    '.....x....x.....',
    '......x..x......',
    '.......xx.......',
    '................',
    '................',
    '................',
  ]),
  mais: i16([
    '................',
    '................',
    '.......xx.......',
    '.......xx.......',
    '.......xx.......',
    '.......xx.......',
    '.......xx.......',
    '..xxxxxxxxxxxx..',
    '..xxxxxxxxxxxx..',
    '.......xx.......',
    '.......xx.......',
    '.......xx.......',
    '.......xx.......',
    '.......xx.......',
    '................',
    '................',
  ]),
  menos: i16([
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '..xxxxxxxxxxxx..',
    '..xxxxxxxxxxxx..',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ]),
  fechar: i16([
    '................',
    '................',
    '..xx........xx..',
    '..xxx......xxx..',
    '...xxx....xxx...',
    '....xxx..xxx....',
    '.....xxxxxx.....',
    '......xxxx......',
    '......xxxx......',
    '.....xxxxxx.....',
    '....xxx..xxx....',
    '...xxx....xxx...',
    '..xxx......xxx..',
    '..xx........xx..',
    '................',
    '................',
  ]),
  'seta-esq': i16([
    '................',
    '................',
    '................',
    '.......x........',
    '......xx........',
    '.....xx.........',
    '....xx..........',
    '...xxxxxxxxxxx..',
    '...xxxxxxxxxxx..',
    '....xx..........',
    '.....xx.........',
    '......xx........',
    '.......x........',
    '................',
    '................',
    '................',
  ]),
  'seta-dir': i16([
    '................',
    '................',
    '................',
    '........x.......',
    '........xx......',
    '.........xx.....',
    '..........xx....',
    '..xxxxxxxxxxx...',
    '..xxxxxxxxxxx...',
    '..........xx....',
    '.........xx.....',
    '........xx......',
    '........x.......',
    '................',
    '................',
    '................',
  ]),
  check: i16([
    '................',
    '................',
    '................',
    '............xx..',
    '...........xxx..',
    '..........xxx...',
    '.........xxx....',
    '..xx....xxx.....',
    '..xxx..xxx......',
    '...xxxxxx.......',
    '....xxxx........',
    '.....xx.........',
    '................',
    '................',
    '................',
    '................',
  ]),
  copiar: i16([
    '................',
    '.....xxxxxxxxx..',
    '.....x.......x..',
    '.....x.......x..',
    '..xxxxxxxx...x..',
    '..x......x...x..',
    '..x......x...x..',
    '..x.xxxx.x...x..',
    '..x......x...x..',
    '..x.xxxx.x...x..',
    '..x......xxxxx..',
    '..x.xxx..x......',
    '..x......x......',
    '..x......x......',
    '..xxxxxxxx......',
    '................',
  ]),
  // Caixa com seta para cima (compartilhar do celular).
  compartilhar: i16([
    '................',
    '.......xx.......',
    '......xxxx......',
    '.....xxxxxx.....',
    '....xx.xx.xx....',
    '.......xx.......',
    '..xxx..xx..xxx..',
    '..x....xx....x..',
    '..x....xx....x..',
    '..x..........x..',
    '..x..........x..',
    '..x..........x..',
    '..x..........x..',
    '..x..........x..',
    '..xxxxxxxxxxxx..',
    '................',
  ]),
  // Estrela da categoria "Tudo".
  estrela: i16([
    '................',
    '.......xx.......',
    '......x..x......',
    '......x..x......',
    '.....x....x.....',
    '.xxxxx....xxxxx.',
    '..x..........x..',
    '...x........x...',
    '....x......x....',
    '....x......x....',
    '...x...xx...x...',
    '...x..x..x..x...',
    '..x..x....x..x..',
    '..x.x......x.x..',
    '..xx........xx..',
    '................',
  ]),

  /* categorias */
  // Lata com a fita ondulada (bebidas importadas).
  lata: i16([
    '................',
    '....xxxxxxxx....',
    '...x..xxx...x...',
    '...xxxxxxxxxx...',
    '...x........x...',
    '...x........x...',
    '...x.......xx...',
    '...x.....xxxx...',
    '...xx..xxxx.x...',
    '...xxxxxx...x...',
    '...xxx......x...',
    '...x........x...',
    '...x........x...',
    '...xxxxxxxxxx...',
    '....xxxxxxxx....',
    '................',
  ]),
  garrafa: i16([
    '......xxxx......',
    '......xxxx......',
    '......x..x......',
    '......x..x......',
    '......x..x......',
    '.....x....x.....',
    '....x......x....',
    '....x......x....',
    '....xxxxxxxx....',
    '....x.xxxx.x....',
    '....x......x....',
    '....xxxxxxxx....',
    '....x......x....',
    '....x......x....',
    '....xxxxxxxx....',
    '................',
  ]),
  // Livreto de seda com a folha saindo pela aba.
  seda: i16([
    '................',
    '................',
    '................',
    '.....xxxxx......',
    '.....x...xx.....',
    '.....x....x.....',
    '.....x....x.....',
    '.xxxxx....xxxxx.',
    '.x............x.',
    '.xxxxxx..xxxxxx.',
    '.x.....xx.....x.',
    '.x............x.',
    '.xxxxxxxxxxxxxx.',
    '................',
    '................',
    '................',
  ]),
  // Piteira: tubo na diagonal, boca com a dobra em zigue-zague e brilho de vidro.
  piteira: i16([
    '................',
    '..........xxx...',
    '.........x...x..',
    '........x.x.x.x.',
    '.......x...x..x.',
    '......x......x..',
    '.....x......x...',
    '....x...x..x....',
    '...x...x..x.....',
    '..x...x..x......',
    '...x....x.......',
    '....x..x........',
    '.....xx.........',
    '................',
    '................',
    '................',
  ]),
  // Alternativa à estrela para "Tudo": grade 2×2.
  tudo: i16([
    '................',
    '................',
    '..xxxxx..xxxxx..',
    '..x...x..x...x..',
    '..x...x..x...x..',
    '..x...x..x...x..',
    '..xxxxx..xxxxx..',
    '................',
    '................',
    '..xxxxx..xxxxx..',
    '..x...x..x...x..',
    '..x...x..x...x..',
    '..x...x..x...x..',
    '..xxxxx..xxxxx..',
    '................',
    '................',
  ]),
} satisfies Record<string, Grade>

export type NomeIcone = keyof typeof iconesBase

export const icones: Record<string, Grade> = iconesBase

/* ───────────────────────── emblemas 24×24 (branco + 2 cinzas) ───────────────────────── */

const tons = { b: '#ffffff', c: '#a8a8a8', e: '#555555' }

export const emblemas: Record<Emblema, Grade> = {
  // RJ: Pão de Açúcar, morro da Urca e o bondinho no cabo, de madrugada.
  'pao-de-acucar': e24(
    [
      '......................c.',
      '...bb.......e...........',
      '..b..............bb.....',
      '..b.....c.......bcee....',
      '...bb..........cceeee...',
      '..............cceeeeee..',
      '..............ceceeeeee.',
      '.......e.....ceceeeeeee.',
      '............ccceeeeeeee.',
      '...........c.ceceeeeeeee',
      '.........cc..cceeeeeeeee',
      '........c.c..ceceeeeeeee',
      '...bbeec..bb.cceeeeeeeee',
      '.ceeeeeee.bb.ceceeeeeeee',
      'ceeeeeeeee..ceceeeeeeeee',
      'cceeeeeeeee.cceeeeeeeeee',
      'ceeeeeeeeee.ceceeeeeeeee',
      'cceeebeeeee.cceeeeeeeeee',
      'cebeeeeebee.ceceeeeeeeee',
      'eeeeeeeeeee.eeeeeeeeeeee',
      '........................',
      '.e.cce.e.e...e.e.e.e.e.e',
      '........................',
      '..cc.....e...e.e.e.e.e.e',
    ],
    tons,
  ),
  // MG / Teófilo Otoni, "capital das pedras preciosas": gema lapidada.
  'pedra-preciosa': e24(
    [
      '....................b...',
      '....................b...',
      '..................bb.bb.',
      '....................b...',
      '.......bbbbbbbbbb...b...',
      '......bbbbbbccccec......',
      '.....bccbbbcccceeec.....',
      '....bcccbbcbccceeeec....',
      '...bccccccbcbceeeeeec...',
      '..bbbbbbbbbbbbcccccccc..',
      '...bccccccbcbceeeeeec...',
      '....bccccbcbcbeeeeec....',
      '.....bccccbcbeeeeec.....',
      '.....bcccccbceeeeec.....',
      '......bcccbcbeeeec......',
      '...c...bcccbceeec.......',
      '..c.c...bccceeec........',
      '...c.....bcbeec.........',
      '..........bcec..........',
      '...........bc...........',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
    tons,
  ),
  // SP: o Copan ondulado entre torres, com antena acesa.
  'predio-sp': e24(
    [
      '.............e..........',
      '.........c......c.......',
      '..b...e.................',
      '..c............ccc......',
      '..c...........cbbbc...c.',
      '..c...c.....ccbeeebc....',
      '..c...bc...cbbeeeeeb....',
      '..ee..ebcccbeeebbbee....',
      '.eeee.eebbbeeebeeebe....',
      '.ecee.beeeeebbeeeeeb....',
      '.eeee.ebeeebeeebbbee....',
      '.eece.eebbbeeebeeebeeeee',
      '.eeee.beeeeebbeeeeebecec',
      '.ecee.ebeeebeeebbbeeeeee',
      '.eeee.eebbbeeebeeebeecec',
      '.eece.beeeeebbeeeeebeeee',
      '.eeee.ebeeebeeebbbeeecec',
      '.ecee.eebbbeeebeeebeeeee',
      '.eeee.beeeeebbeeeeebecec',
      '.eece.ebeeebeeebbbeeeeee',
      '.eeee.eebbbeeebeeebeeeee',
      'cccccccccccccccccccccccc',
      '........................',
      'e..e..e..e..e..e..e..e..',
    ],
    tons,
  ),
  // ES: Convento da Penha no alto do morro.
  'convento-es': e24(
    [
      '..........b.............',
      '.........bbb...e........',
      '.........cb.........c...',
      '...c.....bb.............',
      '.........ee.cccccc......',
      '.........bbcccccccc.....',
      '.........bbbbbbbbbb...e.',
      '.....e...bbbebebebb.....',
      '.........bbbbbbbbeb.....',
      '........cbbbbbbbbebc....',
      '........eeeeeeeececc....',
      '......eeeeeeeeeeececc...',
      '.......eeeeeeeeeeecec...',
      '.....eeeeeeeeeeeeeecec..',
      '.....eeeceeeeeeeeececc..',
      '...eeeeeeeceeeeeeeecec..',
      '...eeeceeeeeeeeeeeeecec.',
      '.eeeeeeeeceeeeeeeeececc.',
      '.eeeceeeeeeeeeeeeeeecec.',
      'eeeeeeeeeeeeeeeeeeeeecec',
      'eeeeeeeeeeeeeeeeeeeeeeee',
      '.e.ecc.e.e.e.e.e.e.e.e..',
      '........................',
      '.....e.e.e.e.e.e.e.e.e..',
    ],
    tons,
  ),
  // SC: ponte pênsil Hercílio Luz, com a corrente descendo até o tabuleiro.
  'ponte-sc': e24(
    [
      '...............c........',
      '.......e.c............c.',
      '.c.cc..............cc...',
      '...bb.......e......bb...',
      '...bbc............cbb...',
      '..cbbec..........c.bbc..',
      '.cebb.ec........c.ebb.c.',
      'ce.cce.ec......c.e.cce.c',
      'e..bb...ec....c.e..bb...',
      '.e.bbe.e.ec..c.e.e.bbe.e',
      '..ebb.e...ecc.e...ebb.e.',
      '.e.bbe.e.e.e.e.e.e.bbe.e',
      'e..bb...e...e...e..bb...',
      'bbbbbbbbbbbbbbbbbbbbbbbb',
      'cccccccccccccccccccccccc',
      '...ee..............ee...',
      '...ee..............ee...',
      '........................',
      'e.e.e.c.c.c.c.c.c.e.e.e.',
      '........................',
      '...e.e.e.e.e.e.e.e..e...',
      '........................',
      '....e....e.e.e.....e....',
      '........................',
    ],
    tons,
  ),
}

/* ───────────────────────── ilustração ───────────────────────── */

// Cliente de rua segurando a garrafa (âmbar é a única cor). Bucket hat, camiseta larga, sem capuz.
const cliente = nova(
  32,
  44,
  [
    '................................',
    '............ccmmmmmm............',
    '...........cmmmmmmmme.....ee....',
    '...........eeeeeeeeee.....aA....',
    '.........cccccccccccccm...aA....',
    '.........mmeeeeeeeeeemm...aA....',
    '............cccccccm.....aaaA...',
    '...........ccceccecmm....waaA...',
    '...........cccccmccmm....waaA...',
    '............cccccmcm.....eeee...',
    '.............ccmmcm......ecce...',
    '..............cccm.......eeee...',
    '..............mmmm.......waaA...',
    '..........wwwcmmmmcwww...aaaA...',
    '........wwwwwccccccwwwwc.aaAA...',
    '.......wwwwwwwwwwwwwwwwwccccm...',
    '......wwwcwwmmwwwwwwwccwccmcm...',
    '......wwwcwwmmwwwwwwcccwcccmm...',
    '......wwwcwwwwwwwwwwcccwcccm....',
    '......wwwcwwwwwwwwwwcccwcccm....',
    '......wwwcwwwwwwwwwwwccwcccm....',
    '......ccccwwwwwwwwwwwccccccm....',
    '.......ccmwwcwwwwwwwwc..cm......',
    '.......ccmwwcwwwwwwwwc..........',
    '.......ccmwwcwwwwwwwwc..........',
    '.......ccmwwwwwwwwwwwc..........',
    '.......ccmwwwwwwwwwwwc..........',
    '.......ccmcccccccccccc..........',
    '.......cmmmeeeeeeeeeee..........',
    '..........meeeeeeeeeee..........',
    '..........meeeeeeeeeee..........',
    '..........meeee..meeee..........',
    '..........mmmme..meeee..........',
    '..........mmeme..meeee..........',
    '..........mmmme..meeee..........',
    '..........meeee..meeee..........',
    '..........meeee..meeee..........',
    '.........mmeeeeemmeeeee.........',
    '.........meeeeeemeeeeee.........',
    '.........wwwwww..wwwwww.........',
    '.......wwcwcwww..wwwcwcww.......',
    '.......cccccccc..cccccccc.......',
    '.......mmmmmmmm..mmmmmmmm.......',
    '......e.e.e.e.e.e.e.e.e.e.......',
  ],
  {
    w: '#ffffff',
    c: '#a8a8a8',
    m: '#6e6e6e',
    e: '#3a3a3a',
    a: '#c8832f',
    A: '#8a5520',
  },
)

export const ilustracoes: Record<'cliente', Grade> = { cliente }

// Em dev, confere tudo já no carregamento (não espera a arte aparecer na tela).
if (import.meta.env?.DEV) {
  for (const [nome, gr] of Object.entries({ ...icones, ...emblemas, ...ilustracoes })) validarGrade(gr, nome)
}
