// GERADO por scripts/gerar-mapa-brasil.mjs — não editar à mão (rode o script de novo).
// Fonte: IBGE, malha das unidades da federação (API de malhas, qualidade mínima), em projeção Albers do Brasil.
//
// Cada caractere é uma célula do mapa: '.' = mar ou fora do Brasil; cada letra é um estado (legenda abaixo).
// O `brasil` é o país inteiro; a `lupa` é o Sudeste + Santa Catarina ampliado, recortado num círculo.

export interface MalhaPixel {
  w: number
  h: number
  linhas: string[]
  /** Onde escrever a sigla de cada UF (célula mais funda do estado), em células. */
  rotulos: Record<string, [number, number]>
}

/** Letra da grade → sigla minúscula da UF. */
export const legenda: Record<string, string> = { a: 'ac', l: 'al', P: 'ap', M: 'am', b: 'ba', c: 'ce', D: 'df', e: 'es', g: 'go', m: 'ma', T: 'mt', S: 'ms', G: 'mg', p: 'pa', B: 'pb', r: 'pr', E: 'pe', i: 'pi', j: 'rj', N: 'rn', R: 'rs', o: 'ro', O: 'rr', C: 'sc', s: 'sp', x: 'se', t: 'to' }

export const brasil: MalhaPixel = {
  w: 92,
  h: 93,
  rotulos: { rr: [28.5, 7.5], ap: [52.5, 8.5], pa: [49.5, 23.5], am: [19.5, 23.5], ma: [68.5, 24.5], pi: [72.5, 31.5], ce: [80.5, 25.5], to: [59.5, 37.5], rn: [87.5, 27.5], pb: [89.5, 30.5], mt: [42.5, 43.5], ac: [7.5, 34.5], pe: [84.5, 33.5], ro: [25.5, 38.5], ba: [75.5, 42.5], al: [87.5, 36.5], se: [85.5, 38.5], go: [56.5, 51.5], mg: [68.5, 57.5], df: [60.5, 50.5], ms: [44.5, 61.5], es: [77.5, 59.5], sp: [58.5, 64.5], rj: [72.5, 66.5], pr: [52.5, 71.5], sc: [56.5, 78.5], rs: [48.5, 83.5] },
  linhas: [
    '...............................O............................................................',
    '..............................OO............................................................',
    '............................OOOOO...................PP......................................',
    '.....................OOO.OOOOOOOO...................PP......................................',
    '......................OOOOOOOOOOO..................PPP......................................',
    '......................OOOOOOOOOO...................PPP......................................',
    '......................OOOOOOOOOOO.........ppp.....PPPPP.....................................',
    '........................OOOOOOOOO.........pppPPPPPPPPPP.....................................',
    '.............MM.......MMMMOOOOOOOO...ppppppppppPPPPPPPPPP...................................',
    '.........MMMMMM......MMMMMOOOOOOOOOpppppppppppppPPPPPPPPP...................................',
    '........MMMMMMMM..M.MMMMMMOOOOOOOOOppppppppppppppPPPPPPPP...................................',
    '..........MMMMMMMMMMMMMMMMOOOOOOOOOppppppppppppppPPPPPPpp...................................',
    '........MMMMMMMMMMMMMMMMMMMOOOOOMMMpppppppppppppppPPPPpppp..................................',
    '........MMMMMMMMMMMMMMMMMMMOOOOOMMMpppppppppppppppPPPppppppp................................',
    '.........MMMMMMMMMMMMMMMMMMOOMMMMMMMpppppppppppppppPppppppppppppp...........................',
    '.........MMMMMMMMMMMMMMMMMMMOMMMMMMMMMppppppppppppppppppppppppppppm.........................',
    '..........MMMMMMMMMMMMMMMMMMMMMMMMMMMMMpppppppppppppppppppppppppppmmm.......................',
    '..........MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMppppppppppppppppppppppppmmmmm......................',
    '..........MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMppppppppppppppppppppppppmmmmm.mm...................',
    '.........MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMpppppppppppppppppppppppmmmmmmmmmmmm................',
    '.........MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMppppppppppppppppppppppppmmmmmmmmmmmmiccccc..........',
    '.........MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMpppppppppppppppppppppppmmmmmmmmmmmiiicccccc.........',
    '.........MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMppppppppppppppppppppppppmmmmmmmmmmiiiiccccccc........',
    '.......M.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMpppppppppppppppppppppppmmmmmmmmmmmiiiicccccccc.......',
    '....MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMppppppppppppppppppppppmmmmmmmmmmmmmiiiiccccccccc......',
    '...MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMppppppppppppppppppppppttmmmmmmmmmmmiiiiiccccccccNN....',
    '..MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMpppppppppppppppppppppppttmmmmmmmmmmmiiiiicccccccNNNNNN.',
    '..MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMpppppppppppppppppppppppttmmmmmmmmmmmiiiiiccccccNNNNNNN.',
    '.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMppppppppppppppppppppppptttmmmmmmmmmmmiiiiicccccNNBNNNNNN',
    '.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMpppppppppppppppppppppttttmmmmmmmmiiiiiiiiiccccBBBNNBBBB',
    'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMTppppppppppppppppppppttttmmmmmmiiiiiiiiiiiccccBBBBBBBBB',
    'aaMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMTpppppppppppppppppppptttttmmmmiiiiiiiiiiiEEEccBBEEBBBBB',
    'aaaaaaaaaaMMMMMMMMMMMMMMoooMMMMMMMMMMTppppppppppppppppppppttttttmmiiiiiiiiiiiiEEEEEEEEBBEEEE',
    '.aaaaaaaaaaMMMMMMMMMMMMoooooMMMMMMMMTTTpppppppppppppppppptttttttmmiiiiiiiiiiiEEEEEEEEEEEEEEE',
    '..aaaaaaaaaaMMMMMMMMMMoooooooTTTTTTTTTTTpppppppppppppppptttttttmmmiiiiiiiiiibEEEbbEEEEEEEEE.',
    '..aaaaaaaaaaaaMMMMMMoooooooooTTTTTTTTTTTTTTTTTTTppppppppttttttttmmiiiiibiibbbbEbbbbbllEElll.',
    '...aaaaaaaaaaaaaaooooooooooooTTTTTTTTTTTTTTTTTTTTTTTTTTTttttttttmmiiiiibbbbbbbbbbbbbxlllll..',
    '.....aa.aaaaaaaaa...oooooooooTTTTTTTTTTTTTTTTTTTTTTTTTTtttttttttttbiiibbbbbbbbbbbbbbxxlll...',
    '........aaaaaaaa....ooooooooooTTTTTTTTTTTTTTTTTTTTTTTTTttttttttttbbiibbbbbbbbbbbbbbbbxxl....',
    '........aaaaaa.......ooooooooooooTTTTTTTTTTTTTTTTTTTTTTtttttttttbbbbbbbbbbbbbbbbbbbbxxx.....',
    '.....................ooooooooooooTTTTTTTTTTTTTTTTTTTTTTttttttttttbbbbbbbbbbbbbbbbbbbxx......',
    '.....................ooooooooooooTTTTTTTTTTTTTTTTTTTTTTttttttttttbbbbbbbbbbbbbbbbbbbb.......',
    '.......................ooooooooooTTTTTTTTTTTTTTTTTTTTTTttttttttttbbbbbbbbbbbbbbbbbbbb.......',
    '..........................oooooooTTTTTTTTTTTTTTTTTTTTTTgttgttttttbbbbbbbbbbbbbbbbbbb........',
    '............................ooooTTTTTTTTTTTTTTTTTTTTTTTgggggttgggbbbbbbbbbbbbbbbbbb.........',
    '...............................oTTTTTTTTTTTTTTTTTTTTTTgggggggggggbbbbbbbbbbbbbbbbb..........',
    '................................TTTTTTTTTTTTTTTTTTTTTTgggggggggggbbbbbbbbbbbbbbbbb..........',
    '................................TTTTTTTTTTTTTTTTTTTTTTgggggggggggbbbGGbbbbbbbbbbb...........',
    '................................TTTTTTTTTTTTTTTTTTTTTgggggggggggGbbGGGGGbbbbbbbbb...........',
    '................................TTTTTTTTTTTTTTTTTTTTgggggggggggGGGGGGGGGGGbbbbbbb...........',
    '.................................TTTTTTTTTTTTTTTTTTTggggggggDDgGGGGGGGGGGGGGbbbbb...........',
    '.................................TTTTTTTTTTTTTTTTTggggggggggDDGGGGGGGGGGGGGGGGbbb...........',
    '.....................................TTTTTTTTTTTTTggggggggggggGGGGGGGGGGGGGGGGGbb...........',
    '.....................................TTTTTTTTTTTTgggggggggggggGGGGGGGGGGGGGGGGbbb...........',
    '.....................................TTTTSSTTTTTTgggggggggggggGGGGGGGGGGGGGGGbbbb...........',
    '......................................SSSSSSSSSTTgggggggggggggGGGGGGGGGGGGGGGGbbb...........',
    '.......................................SSSSSSSSSSgggggggggggggGGGGGGGGGGGGGGGebb............',
    '......................................SSSSSSSSSSSSggggggGGGGGGGGGGGGGGGGGGGGeee.............',
    '......................................SSSSSSSSSSSSSSgggGGGGGGGGGGGGGGGGGGGGGeee.............',
    '......................................SSSSSSSSSSSSSSSSGGGGGGGGGGGGGGGGGGGGGGeee.............',
    '......................................SSSSSSSSSSSSSSSSssGGGGGGGGGGGGGGGGGGGGeee.............',
    '......................................SSSSSSSSSSSSSSSsssssssssGGGGGGGGGGGGGeee..............',
    '......................................SSSSSSSSSSSSSSssssssssssGGGGGGGGGGGGeeee..............',
    '......................................SSSSSSSSSSSSSSssssssssssGGGGGGGGGGGGeee...............',
    '......................................SSSSSSSSSSSSSssssssssssssGGGGGGGGGGjjj................',
    '......................................SSSSSSSSSSSSSssssssssssssGGGGGGGGGGjjj................',
    '...........................................SSSSSSSsssssssssssssGGGGGjjjjjjj.................',
    '...........................................SSSSSrrrrrrssssssssssGsssjjjjjj..................',
    '...........................................SSSSSrrrrrrrrsssssssssss.........................',
    '...........................................SSSSrrrrrrrrrrssssssssss.........................',
    '..............................................rrrrrrrrrrrsssssss............................',
    '..............................................rrrrrrrrrrrsssss..............................',
    '..............................................rrrrrrrrrrrrrss...............................',
    '..............................................rrrrrrrrrrrrrr................................',
    '...............................................rrrrrrrrrrrr.................................',
    '...............................................rrrrrrrCCrCC.................................',
    '...............................................CCCCCCCCCCCC.................................',
    '...............................................CCCCCCCCCCCC.................................',
    '.............................................RRRRRRRCCCCCCC.................................',
    '............................................RRRRRRRRRCCCCCC.................................',
    '...........................................RRRRRRRRRRRCCCCC.................................',
    '..........................................RRRRRRRRRRRRRRCC..................................',
    '.........................................RRRRRRRRRRRRRRRC...................................',
    '........................................RRRRRRRRRRRRRRRR....................................',
    '.......................................RRRRRRRRRRRRRRRR.....................................',
    '..........................................RRRRRRRRRRR.R.....................................',
    '..........................................RRRRRRRRRRRR......................................',
    '.............................................RRRRRRR........................................',
    '..............................................RRRRR.........................................',
    '...............................................RRRR.........................................',
    '................................................R...........................................',
    '................................................RR..........................................',
    '................................................R...........................................',
  ],
}

/** A lupa: grade quadrada (só o círculo inscrito tem terra). `noBrasil` = centro e raio dela no mapa inteiro, em células. */
export const lupa: MalhaPixel & { noBrasil: { cx: number; cy: number; raio: number } } = {
  w: 64,
  h: 64,
  noBrasil: { cx: 63.23, cy: 65.04, raio: 21.77 },
  rotulos: { ba: [39.5, 3.5], go: [21.5, 13.5], mt: [11.5, 11.5], mg: [39.5, 20.5], ms: [7.5, 27.5], es: [52.5, 25.5], sp: [26.5, 34.5], rj: [45.5, 34.5], pr: [15.5, 41.5], sc: [21.5, 51.5], rs: [15.5, 55.5] },
  linhas: [
    '..........................ttttttttbbbb..........................',
    '......................gggggttttgggbbbbbbbb......................',
    '....................ggggggggggggggbbbbbbbbbb....................',
    '.................TTgggggggggggggggbbbbbbbbbbbbb.................',
    '................TTTgggggggggggggggbbbbbbbbbbbbbb................',
    '..............TTTTgggggggggggggggggbbbbbbbbbbbbbbb..............',
    '.............TTTTTgggggggggggggggggbbbbGGGbbbbbbbbb.............',
    '...........TTTTTTTgggggggggggggggGgbbGGGGGGbGbbbbbbbb...........',
    '..........TTTTTTggggggggggggggggGGGbGGGGGGGGGGbbbbbbbb..........',
    '.........TTTTTTTggggggggggggggggGGGGGGGGGGGGGGGGGbbbbbb.........',
    '........TTTTTTTggggggggggggDDDggGGGGGGGGGGGGGGGGGGbbbbbb........',
    '.......TTTTTTTgggggggggggggDDDgGGGGGGGGGGGGGGGGGGGGGGbbbb.......',
    '.......TTTTTTgggggggggggggggggGGGGGGGGGGGGGGGGGGGGGGGGGbb.......',
    '......TTTTTTggggggggggggggggggGGGGGGGGGGGGGGGGGGGGGGGGGbbb......',
    '.....TTTTTTggggggggggggggggggggGGGGGGGGGGGGGGGGGGGGGGGbbbb......',
    '.....TTTTTTggggggggggggggggggggGGGGGGGGGGGGGGGGGGGGGGbbbbb......',
    '....TTTTSTTgggggggggggggggggggGGGGGGGGGGGGGGGGGGGGGGGbbbb.......',
    '...SSSSSSTTgggggggggggggggggggGGGGGGGGGGGGGGGGGGGGGGGbbbb.......',
    '...SSSSSSTTgggggggggggggggggggGGGGGGGGGGGGGGGGGGGGGGGGbbb.......',
    '...SSSSSSSSgggggggggggggggggggGGGGGGGGGGGGGGGGGGGGGGeebbb.......',
    '..SSSSSSSSSSggggggggggggGGGGGGGGGGGGGGGGGGGGGGGGGGGeeeeb........',
    '..SSSSSSSSSSSSggggggGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGeeee.........',
    '.SSSSSSSSSSSSSSSgggGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGeeee.........',
    '.SSSSSSSSSSSSSSSSSGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGeeee.........',
    '.SSSSSSSSSSSSSSSSSGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGeeee.........',
    '.SSSSSSSSSSSSSSSSSGsssGGGGGGGGGGGGGGGGGGGGGGGGGGGGeeeee.........',
    'SSSSSSSSSSSSSSSSSsssssssGsssssGGGGGGGGGGGGGGGGGGGGeeee..........',
    'SSSSSSSSSSSSSSSSssssssssssssssGGGGGGGGGGGGGGGGGGeeeee...........',
    'SSSSSSSSSSSSSSSSssssssssssssssGGGGGGGGGGGGGGGGGGeeeee...........',
    'SSSSSSSSSSSSSSSsssssssssssssssGGGGGGGGGGGGGGGGGGeeee............',
    'SSSSSSSSSSSSSSSssssssssssssssssGGGGGGGGGGGGGGGGjjee.............',
    'SSSSSSSSSSSSSSssssssssssssssssssGGGGGGGGGGGGGGjjjjj.............',
    'SSSSSSSSSSSSSSssssssssssssssssssGGGGGGGGGGGGGGjjjjj.............',
    'SSSSSSSSSSSSSsssssssssssssssssssGGGGGGGGGGjGjjjjjjj.............',
    '..SSSSSSSSSsssssssssssssssssssssGGGGGGjjjjjjjjjjj...............',
    '...SSSSSSSrrrrrrrrsssssssssssssssGGsssssjjjjjjj.................',
    '...SSSSSSrrrrrrrrrrrrrssssssssssssssssjjjjjjjjj.................',
    '...SSSSSSrrrrrrrrrrrrrssssssssssssssssj.........................',
    '...SSSSSrrrrrrrrrrrrrrsssssssssssssss...........................',
    '...SS.SSrrrrrrrrrrrrrrssssssssssss.s............................',
    '.......rrrrrrrrrrrrrrrrsssssssss................................',
    '.......rrrrrrrrrrrrrrrrssssssss.................................',
    '.......rrrrrrrrrrrrrrrrrrssss...................................',
    '......rrrrrrrrrrrrrrrrrrrrss....................................',
    '......rrrrrrrrrrrrrrrrrrrrr.....................................',
    '........rrrrrrrrrrrrrrrrrr......................................',
    '........rrrrrrrrrrrrrrrrrr......................................',
    '.........rrrrrrrrrCCCCCCCC......................................',
    '.........CCCCCrrrCCCCCCCC.......................................',
    '.........CCCCCCCCCCCCCCCC.......................................',
    '........RCCCCCCCCCCCCCCCC.......................................',
    '.......RRRRRRRCCCCCCCCCCCC......................................',
    '.......RRRRRRRRRCCCCCCCCCC......................................',
    '........RRRRRRRRRRCCCCCCC.......................................',
    '.........RRRRRRRRRCCCCCCC.......................................',
    '..........RRRRRRRRRRRCCCC.......................................',
    '...........RRRRRRRRRRCC.........................................',
    '.............RRRRRRRRC..........................................',
    '..............RRRRRRRR..........................................',
    '................RRRRR...........................................',
    '.................RRR............................................',
    '................................................................',
    '................................................................',
    '................................................................',
  ],
}

/** Cidades atendidas (slug de canais.ts): posição no mapa inteiro e na lupa, em células. */
export const cidadesNoMapa: Record<string, { brasil: [number, number]; lupa: [number, number] }> = { 'teofilo-otoni': { brasil: [75.12, 56.15], lupa: [49.48, 18.92] }, 'rio-de-janeiro': { brasil: [70.83, 68.14], lupa: [43.18, 36.56] } }
