// Ícones das telas de Equipe e Clientes, no traço dos outros (16×16, 'x' = currentColor).
import type { Grade } from '../../arte/pixel/grades'

function g(linhas: string[]): Grade {
  return { w: linhas[0]?.length ?? 0, h: linhas.length, linhas }
}

export const iconesContas: Record<string, Grade> = {
  // Equipe: duas pessoas lado a lado (contorno; cheia na seção acesa).
  equipe: g([
    '................',
    '..xxx.....xxx...',
    '.x...x...x...x..',
    '.x...x...x...x..',
    '.x...x...x...x..',
    '..xxx.....xxx...',
    '................',
    '.xxxxx...xxxxx..',
    'x.....x.x.....x.',
    'x.....x.x.....x.',
    'x.....x.x.....x.',
    'x.....x.x.....x.',
    'xxxxxxx.xxxxxxx.',
    '................',
    '................',
    '................',
  ]),
  'equipe-cheia': g([
    '................',
    '..xxx.....xxx...',
    '.xxxxx...xxxxx..',
    '.xxxxx...xxxxx..',
    '.xxxxx...xxxxx..',
    '..xxx.....xxx...',
    '................',
    '.xxxxx...xxxxx..',
    'xxxxxxx.xxxxxxx.',
    'xxxxxxx.xxxxxxx.',
    'xxxxxxx.xxxxxxx.',
    'xxxxxxx.xxxxxxx.',
    'xxxxxxx.xxxxxxx.',
    '................',
    '................',
    '................',
  ]),
  // Clientes: a ficha de contato (a pessoa e as linhas do lado).
  clientes: g([
    '................',
    'xxxxxxxxxxxxxxxx',
    'x..............x',
    'x..xxx.........x',
    'x.x...x..xxxxx.x',
    'x.x...x........x',
    'x.x...x..xxxx..x',
    'x..xxx.........x',
    'x.xxxxx..xxxxx.x',
    'xx.....x.......x',
    'xx.....x.......x',
    'xxxxxxxxxxxxxxxx',
    '................',
    '................',
    '................',
    '................',
  ]),
  'clientes-cheio': g([
    '................',
    'xxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxx',
    'xx...xxxxxxxxxxx',
    'x.....xx.....x.x',
    'x.....xxxxxxxx.x',
    'x.....xx....xx.x',
    'xx...xxxxxxxxx.x',
    'x.....xx.....x.x',
    'x.....xxxxxxxx.x',
    'x.....xxxxxxxx.x',
    'xxxxxxxxxxxxxxxx',
    '................',
    '................',
    '................',
    '................',
  ]),
  // Chave: senha provisória, redefinir a senha.
  chave: g([
    '................',
    '..xxxx..........',
    '.x....x.........',
    'x......x........',
    'x..xx..x........',
    'x..xx..xxxxxxxxx',
    'x......x....x..x',
    '.x....x.....x..x',
    '..xxxx..........',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ]),
}
